; Minecraft Steve model with walking animation - generated by gen_steve.py
; 6 boxes, 48 vertices, 72 triangles, 24 animation frames

STEVE_NUM_VERTICES = 48
STEVE_NUM_FACES_0 = 72      ; All faces in single mesh
STEVE_NUM_FACES_1 = 0
STEVE_NUM_FRAMES = 24

steve_vx_0
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_0
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $e2, $e2, $e2, $e2, $88, $88, $88, $88
        .byte $e2, $e2, $e2, $e2, $88, $88, $88, $88
steve_vz_0
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f

steve_vx_1
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_1
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $3a, $3a, $3e, $3e, $e1, $e1, $e5, $e5
        .byte $3e, $3e, $3a, $3a, $e5, $e5, $e1, $e1
        .byte $e4, $e4, $e0, $e0, $8b, $8b, $87, $87
        .byte $e0, $e0, $e4, $e4, $87, $87, $8b, $8b
steve_vz_1
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $fd, $fd, $1b, $1b
        .byte $f1, $f1, $0f, $0f, $e5, $e5, $03, $03
        .byte $f1, $f1, $0f, $0f, $e5, $e5, $03, $03
        .byte $f1, $f1, $0f, $0f, $fd, $fd, $1b, $1b

steve_vx_2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_2
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $38, $38, $40, $40, $e1, $e1, $e9, $e9
        .byte $40, $40, $38, $38, $e9, $e9, $e1, $e1
        .byte $e6, $e6, $de, $de, $8f, $8f, $87, $87
        .byte $de, $de, $e6, $e6, $87, $87, $8f, $8f
steve_vz_2
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f2, $f2, $0e, $0e, $09, $09, $26, $26
        .byte $f2, $f2, $0e, $0e, $da, $da, $f7, $f7
        .byte $f2, $f2, $0e, $0e, $da, $da, $f7, $f7
        .byte $f2, $f2, $0e, $0e, $09, $09, $26, $26

steve_vx_3
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_3
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $37, $37, $41, $41, $e3, $e3, $ee, $ee
        .byte $41, $41, $37, $37, $ee, $ee, $e3, $e3
        .byte $e7, $e7, $dd, $dd, $94, $94, $89, $89
        .byte $dd, $dd, $e7, $e7, $89, $89, $94, $94
steve_vz_3
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f2, $f2, $0e, $0e, $13, $13, $2f, $2f
        .byte $f2, $f2, $0e, $0e, $d1, $d1, $ed, $ed
        .byte $f2, $f2, $0e, $0e, $d1, $d1, $ed, $ed
        .byte $f2, $f2, $0e, $0e, $13, $13, $2f, $2f

steve_vx_4
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_4
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $35, $35, $43, $43, $e5, $e5, $f2, $f2
        .byte $43, $43, $35, $35, $f2, $f2, $e5, $e5
        .byte $e9, $e9, $db, $db, $98, $98, $8b, $8b
        .byte $db, $db, $e9, $e9, $8b, $8b, $98, $98
steve_vz_4
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f3, $f3, $0d, $0d, $1a, $1a, $35, $35
        .byte $f3, $f3, $0d, $0d, $cb, $cb, $e6, $e6
        .byte $f3, $f3, $0d, $0d, $cb, $cb, $e6, $e6
        .byte $f3, $f3, $0d, $0d, $1a, $1a, $35, $35

steve_vx_5
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_5
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $35, $35, $43, $43, $e6, $e6, $f5, $f5
        .byte $43, $43, $35, $35, $f5, $f5, $e6, $e6
        .byte $e9, $e9, $db, $db, $9b, $9b, $8c, $8c
        .byte $db, $db, $e9, $e9, $8c, $8c, $9b, $9b
steve_vz_5
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f3, $f3, $0d, $0d, $1e, $1e, $39, $39
        .byte $f3, $f3, $0d, $0d, $c7, $c7, $e2, $e2
        .byte $f3, $f3, $0d, $0d, $c7, $c7, $e2, $e2
        .byte $f3, $f3, $0d, $0d, $1e, $1e, $39, $39

steve_vx_6
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_6
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $34, $34, $44, $44, $e7, $e7, $f6, $f6
        .byte $44, $44, $34, $34, $f6, $f6, $e7, $e7
        .byte $ea, $ea, $da, $da, $9c, $9c, $8d, $8d
        .byte $da, $da, $ea, $ea, $8d, $8d, $9c, $9c
steve_vz_6
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f3, $f3, $0d, $0d, $20, $20, $3a, $3a
        .byte $f3, $f3, $0d, $0d, $c6, $c6, $e0, $e0
        .byte $f3, $f3, $0d, $0d, $c6, $c6, $e0, $e0
        .byte $f3, $f3, $0d, $0d, $20, $20, $3a, $3a

steve_vx_7
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_7
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $35, $35, $43, $43, $e6, $e6, $f5, $f5
        .byte $43, $43, $35, $35, $f5, $f5, $e6, $e6
        .byte $e9, $e9, $db, $db, $9b, $9b, $8c, $8c
        .byte $db, $db, $e9, $e9, $8c, $8c, $9b, $9b
steve_vz_7
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f3, $f3, $0d, $0d, $1e, $1e, $39, $39
        .byte $f3, $f3, $0d, $0d, $c7, $c7, $e2, $e2
        .byte $f3, $f3, $0d, $0d, $c7, $c7, $e2, $e2
        .byte $f3, $f3, $0d, $0d, $1e, $1e, $39, $39

steve_vx_8
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_8
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $35, $35, $43, $43, $e5, $e5, $f2, $f2
        .byte $43, $43, $35, $35, $f2, $f2, $e5, $e5
        .byte $e9, $e9, $db, $db, $98, $98, $8b, $8b
        .byte $db, $db, $e9, $e9, $8b, $8b, $98, $98
steve_vz_8
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f3, $f3, $0d, $0d, $1a, $1a, $35, $35
        .byte $f3, $f3, $0d, $0d, $cb, $cb, $e6, $e6
        .byte $f3, $f3, $0d, $0d, $cb, $cb, $e6, $e6
        .byte $f3, $f3, $0d, $0d, $1a, $1a, $35, $35

steve_vx_9
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_9
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $37, $37, $41, $41, $e3, $e3, $ee, $ee
        .byte $41, $41, $37, $37, $ee, $ee, $e3, $e3
        .byte $e7, $e7, $dd, $dd, $94, $94, $89, $89
        .byte $dd, $dd, $e7, $e7, $89, $89, $94, $94
steve_vz_9
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f2, $f2, $0e, $0e, $13, $13, $2f, $2f
        .byte $f2, $f2, $0e, $0e, $d1, $d1, $ed, $ed
        .byte $f2, $f2, $0e, $0e, $d1, $d1, $ed, $ed
        .byte $f2, $f2, $0e, $0e, $13, $13, $2f, $2f

steve_vx_10
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_10
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $38, $38, $40, $40, $e1, $e1, $e9, $e9
        .byte $40, $40, $38, $38, $e9, $e9, $e1, $e1
        .byte $e6, $e6, $de, $de, $8f, $8f, $87, $87
        .byte $de, $de, $e6, $e6, $87, $87, $8f, $8f
steve_vz_10
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f2, $f2, $0e, $0e, $09, $09, $26, $26
        .byte $f2, $f2, $0e, $0e, $da, $da, $f7, $f7
        .byte $f2, $f2, $0e, $0e, $da, $da, $f7, $f7
        .byte $f2, $f2, $0e, $0e, $09, $09, $26, $26

steve_vx_11
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_11
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $3a, $3a, $3e, $3e, $e1, $e1, $e5, $e5
        .byte $3e, $3e, $3a, $3a, $e5, $e5, $e1, $e1
        .byte $e4, $e4, $e0, $e0, $8b, $8b, $87, $87
        .byte $e0, $e0, $e4, $e4, $87, $87, $8b, $8b
steve_vz_11
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $fd, $fd, $1b, $1b
        .byte $f1, $f1, $0f, $0f, $e5, $e5, $03, $03
        .byte $f1, $f1, $0f, $0f, $e5, $e5, $03, $03
        .byte $f1, $f1, $0f, $0f, $fd, $fd, $1b, $1b

steve_vx_12
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_12
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $e2, $e2, $e2, $e2, $88, $88, $88, $88
        .byte $e2, $e2, $e2, $e2, $88, $88, $88, $88
steve_vz_12
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f

steve_vx_13
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_13
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $3e, $3e, $3a, $3a, $e5, $e5, $e1, $e1
        .byte $3a, $3a, $3e, $3e, $e1, $e1, $e5, $e5
        .byte $e0, $e0, $e4, $e4, $87, $87, $8b, $8b
        .byte $e4, $e4, $e0, $e0, $8b, $8b, $87, $87
steve_vz_13
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $e5, $e5, $03, $03
        .byte $f1, $f1, $0f, $0f, $fd, $fd, $1b, $1b
        .byte $f1, $f1, $0f, $0f, $fd, $fd, $1b, $1b
        .byte $f1, $f1, $0f, $0f, $e5, $e5, $03, $03

steve_vx_14
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_14
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $40, $40, $38, $38, $e9, $e9, $e1, $e1
        .byte $38, $38, $40, $40, $e1, $e1, $e9, $e9
        .byte $de, $de, $e6, $e6, $87, $87, $8f, $8f
        .byte $e6, $e6, $de, $de, $8f, $8f, $87, $87
steve_vz_14
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f2, $f2, $0e, $0e, $da, $da, $f7, $f7
        .byte $f2, $f2, $0e, $0e, $09, $09, $26, $26
        .byte $f2, $f2, $0e, $0e, $09, $09, $26, $26
        .byte $f2, $f2, $0e, $0e, $da, $da, $f7, $f7

steve_vx_15
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_15
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $41, $41, $37, $37, $ee, $ee, $e3, $e3
        .byte $37, $37, $41, $41, $e3, $e3, $ee, $ee
        .byte $dd, $dd, $e7, $e7, $89, $89, $94, $94
        .byte $e7, $e7, $dd, $dd, $94, $94, $89, $89
steve_vz_15
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f2, $f2, $0e, $0e, $d1, $d1, $ed, $ed
        .byte $f2, $f2, $0e, $0e, $13, $13, $2f, $2f
        .byte $f2, $f2, $0e, $0e, $13, $13, $2f, $2f
        .byte $f2, $f2, $0e, $0e, $d1, $d1, $ed, $ed

steve_vx_16
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_16
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $43, $43, $35, $35, $f2, $f2, $e5, $e5
        .byte $35, $35, $43, $43, $e5, $e5, $f2, $f2
        .byte $db, $db, $e9, $e9, $8b, $8b, $98, $98
        .byte $e9, $e9, $db, $db, $98, $98, $8b, $8b
steve_vz_16
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f3, $f3, $0d, $0d, $cb, $cb, $e6, $e6
        .byte $f3, $f3, $0d, $0d, $1a, $1a, $35, $35
        .byte $f3, $f3, $0d, $0d, $1a, $1a, $35, $35
        .byte $f3, $f3, $0d, $0d, $cb, $cb, $e6, $e6

steve_vx_17
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_17
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $43, $43, $35, $35, $f5, $f5, $e6, $e6
        .byte $35, $35, $43, $43, $e6, $e6, $f5, $f5
        .byte $db, $db, $e9, $e9, $8c, $8c, $9b, $9b
        .byte $e9, $e9, $db, $db, $9b, $9b, $8c, $8c
steve_vz_17
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f3, $f3, $0d, $0d, $c7, $c7, $e2, $e2
        .byte $f3, $f3, $0d, $0d, $1e, $1e, $39, $39
        .byte $f3, $f3, $0d, $0d, $1e, $1e, $39, $39
        .byte $f3, $f3, $0d, $0d, $c7, $c7, $e2, $e2

steve_vx_18
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_18
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $44, $44, $34, $34, $f6, $f6, $e7, $e7
        .byte $34, $34, $44, $44, $e7, $e7, $f6, $f6
        .byte $da, $da, $ea, $ea, $8d, $8d, $9c, $9c
        .byte $ea, $ea, $da, $da, $9c, $9c, $8d, $8d
steve_vz_18
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f3, $f3, $0d, $0d, $c6, $c6, $e0, $e0
        .byte $f3, $f3, $0d, $0d, $20, $20, $3a, $3a
        .byte $f3, $f3, $0d, $0d, $20, $20, $3a, $3a
        .byte $f3, $f3, $0d, $0d, $c6, $c6, $e0, $e0

steve_vx_19
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_19
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $43, $43, $35, $35, $f5, $f5, $e6, $e6
        .byte $35, $35, $43, $43, $e6, $e6, $f5, $f5
        .byte $db, $db, $e9, $e9, $8c, $8c, $9b, $9b
        .byte $e9, $e9, $db, $db, $9b, $9b, $8c, $8c
steve_vz_19
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f3, $f3, $0d, $0d, $c7, $c7, $e2, $e2
        .byte $f3, $f3, $0d, $0d, $1e, $1e, $39, $39
        .byte $f3, $f3, $0d, $0d, $1e, $1e, $39, $39
        .byte $f3, $f3, $0d, $0d, $c7, $c7, $e2, $e2

steve_vx_20
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_20
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $43, $43, $35, $35, $f2, $f2, $e5, $e5
        .byte $35, $35, $43, $43, $e5, $e5, $f2, $f2
        .byte $db, $db, $e9, $e9, $8b, $8b, $98, $98
        .byte $e9, $e9, $db, $db, $98, $98, $8b, $8b
steve_vz_20
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f3, $f3, $0d, $0d, $cb, $cb, $e6, $e6
        .byte $f3, $f3, $0d, $0d, $1a, $1a, $35, $35
        .byte $f3, $f3, $0d, $0d, $1a, $1a, $35, $35
        .byte $f3, $f3, $0d, $0d, $cb, $cb, $e6, $e6

steve_vx_21
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_21
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $41, $41, $37, $37, $ee, $ee, $e3, $e3
        .byte $37, $37, $41, $41, $e3, $e3, $ee, $ee
        .byte $dd, $dd, $e7, $e7, $89, $89, $94, $94
        .byte $e7, $e7, $dd, $dd, $94, $94, $89, $89
steve_vz_21
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f2, $f2, $0e, $0e, $d1, $d1, $ed, $ed
        .byte $f2, $f2, $0e, $0e, $13, $13, $2f, $2f
        .byte $f2, $f2, $0e, $0e, $13, $13, $2f, $2f
        .byte $f2, $f2, $0e, $0e, $d1, $d1, $ed, $ed

steve_vx_22
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_22
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $40, $40, $38, $38, $e9, $e9, $e1, $e1
        .byte $38, $38, $40, $40, $e1, $e1, $e9, $e9
        .byte $de, $de, $e6, $e6, $87, $87, $8f, $8f
        .byte $e6, $e6, $de, $de, $8f, $8f, $87, $87
steve_vz_22
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f2, $f2, $0e, $0e, $da, $da, $f7, $f7
        .byte $f2, $f2, $0e, $0e, $09, $09, $26, $26
        .byte $f2, $f2, $0e, $0e, $09, $09, $26, $26
        .byte $f2, $f2, $0e, $0e, $da, $da, $f7, $f7

steve_vx_23
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_23
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $3e, $3e, $3a, $3a, $e5, $e5, $e1, $e1
        .byte $3a, $3a, $3e, $3e, $e1, $e1, $e5, $e5
        .byte $e0, $e0, $e4, $e4, $87, $87, $8b, $8b
        .byte $e4, $e4, $e0, $e0, $8b, $8b, $87, $87
steve_vz_23
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $e5, $e5, $03, $03
        .byte $f1, $f1, $0f, $0f, $fd, $fd, $1b, $1b
        .byte $f1, $f1, $0f, $0f, $fd, $fd, $1b, $1b
        .byte $f1, $f1, $0f, $0f, $e5, $e5, $03, $03

; Pointer tables for animation frames
steve_vx_lo
        .byte <steve_vx_0
        .byte <steve_vx_1
        .byte <steve_vx_2
        .byte <steve_vx_3
        .byte <steve_vx_4
        .byte <steve_vx_5
        .byte <steve_vx_6
        .byte <steve_vx_7
        .byte <steve_vx_8
        .byte <steve_vx_9
        .byte <steve_vx_10
        .byte <steve_vx_11
        .byte <steve_vx_12
        .byte <steve_vx_13
        .byte <steve_vx_14
        .byte <steve_vx_15
        .byte <steve_vx_16
        .byte <steve_vx_17
        .byte <steve_vx_18
        .byte <steve_vx_19
        .byte <steve_vx_20
        .byte <steve_vx_21
        .byte <steve_vx_22
        .byte <steve_vx_23
steve_vx_hi
        .byte >steve_vx_0
        .byte >steve_vx_1
        .byte >steve_vx_2
        .byte >steve_vx_3
        .byte >steve_vx_4
        .byte >steve_vx_5
        .byte >steve_vx_6
        .byte >steve_vx_7
        .byte >steve_vx_8
        .byte >steve_vx_9
        .byte >steve_vx_10
        .byte >steve_vx_11
        .byte >steve_vx_12
        .byte >steve_vx_13
        .byte >steve_vx_14
        .byte >steve_vx_15
        .byte >steve_vx_16
        .byte >steve_vx_17
        .byte >steve_vx_18
        .byte >steve_vx_19
        .byte >steve_vx_20
        .byte >steve_vx_21
        .byte >steve_vx_22
        .byte >steve_vx_23

steve_vy_lo
        .byte <steve_vy_0
        .byte <steve_vy_1
        .byte <steve_vy_2
        .byte <steve_vy_3
        .byte <steve_vy_4
        .byte <steve_vy_5
        .byte <steve_vy_6
        .byte <steve_vy_7
        .byte <steve_vy_8
        .byte <steve_vy_9
        .byte <steve_vy_10
        .byte <steve_vy_11
        .byte <steve_vy_12
        .byte <steve_vy_13
        .byte <steve_vy_14
        .byte <steve_vy_15
        .byte <steve_vy_16
        .byte <steve_vy_17
        .byte <steve_vy_18
        .byte <steve_vy_19
        .byte <steve_vy_20
        .byte <steve_vy_21
        .byte <steve_vy_22
        .byte <steve_vy_23
steve_vy_hi
        .byte >steve_vy_0
        .byte >steve_vy_1
        .byte >steve_vy_2
        .byte >steve_vy_3
        .byte >steve_vy_4
        .byte >steve_vy_5
        .byte >steve_vy_6
        .byte >steve_vy_7
        .byte >steve_vy_8
        .byte >steve_vy_9
        .byte >steve_vy_10
        .byte >steve_vy_11
        .byte >steve_vy_12
        .byte >steve_vy_13
        .byte >steve_vy_14
        .byte >steve_vy_15
        .byte >steve_vy_16
        .byte >steve_vy_17
        .byte >steve_vy_18
        .byte >steve_vy_19
        .byte >steve_vy_20
        .byte >steve_vy_21
        .byte >steve_vy_22
        .byte >steve_vy_23

steve_vz_lo
        .byte <steve_vz_0
        .byte <steve_vz_1
        .byte <steve_vz_2
        .byte <steve_vz_3
        .byte <steve_vz_4
        .byte <steve_vz_5
        .byte <steve_vz_6
        .byte <steve_vz_7
        .byte <steve_vz_8
        .byte <steve_vz_9
        .byte <steve_vz_10
        .byte <steve_vz_11
        .byte <steve_vz_12
        .byte <steve_vz_13
        .byte <steve_vz_14
        .byte <steve_vz_15
        .byte <steve_vz_16
        .byte <steve_vz_17
        .byte <steve_vz_18
        .byte <steve_vz_19
        .byte <steve_vz_20
        .byte <steve_vz_21
        .byte <steve_vz_22
        .byte <steve_vz_23
steve_vz_hi
        .byte >steve_vz_0
        .byte >steve_vz_1
        .byte >steve_vz_2
        .byte >steve_vz_3
        .byte >steve_vz_4
        .byte >steve_vz_5
        .byte >steve_vz_6
        .byte >steve_vz_7
        .byte >steve_vz_8
        .byte >steve_vz_9
        .byte >steve_vz_10
        .byte >steve_vz_11
        .byte >steve_vz_12
        .byte >steve_vz_13
        .byte >steve_vz_14
        .byte >steve_vz_15
        .byte >steve_vz_16
        .byte >steve_vz_17
        .byte >steve_vz_18
        .byte >steve_vz_19
        .byte >steve_vz_20
        .byte >steve_vz_21
        .byte >steve_vz_22
        .byte >steve_vz_23

; Face indices (constant across all frames)
steve_fi_0
        .byte $00, $00, $02, $02, $00, $00, $04, $04, $01, $01, $00, $00
        .byte $08, $08, $0a, $0a, $08, $08, $0c, $0c, $09, $09, $08, $08
        .byte $10, $10, $12, $12, $10, $10, $14, $14, $11, $11, $10, $10
        .byte $18, $18, $1a, $1a, $18, $18, $1c, $1c, $19, $19, $18, $18
        .byte $20, $20, $22, $22, $20, $20, $24, $24, $21, $21, $20, $20
        .byte $28, $28, $2a, $2a, $28, $28, $2c, $2c, $29, $29, $28, $28

steve_fj_0
        .byte $01, $05, $03, $07, $03, $02, $05, $06, $02, $06, $04, $07
        .byte $09, $0d, $0b, $0f, $0b, $0a, $0d, $0e, $0a, $0e, $0c, $0f
        .byte $11, $15, $13, $17, $13, $12, $15, $16, $12, $16, $14, $17
        .byte $19, $1d, $1b, $1f, $1b, $1a, $1d, $1e, $1a, $1e, $1c, $1f
        .byte $21, $25, $23, $27, $23, $22, $25, $26, $22, $26, $24, $27
        .byte $29, $2d, $2b, $2f, $2b, $2a, $2d, $2e, $2a, $2e, $2c, $2f

steve_fk_0
        .byte $05, $04, $07, $06, $02, $01, $06, $07, $06, $05, $07, $03
        .byte $0d, $0c, $0f, $0e, $0a, $09, $0e, $0f, $0e, $0d, $0f, $0b
        .byte $15, $14, $17, $16, $12, $11, $16, $17, $16, $15, $17, $13
        .byte $1d, $1c, $1f, $1e, $1a, $19, $1e, $1f, $1e, $1d, $1f, $1b
        .byte $25, $24, $27, $26, $22, $21, $26, $27, $26, $25, $27, $23
        .byte $2d, $2c, $2f, $2e, $2a, $29, $2e, $2f, $2e, $2d, $2f, $2b

; Empty second mesh
steve_fi_1
steve_fj_1
steve_fk_1

; Face colors
steve_fcol_0
        .byte $01, $02, $03, $01, $02, $03, $01, $02, $03, $01, $02, $03
        .byte $01, $02, $03, $01, $02, $03, $01, $02, $03, $01, $02, $03
        .byte $01, $02, $03, $01, $02, $03, $01, $02, $03, $01, $02, $03
        .byte $01, $02, $03, $01, $02, $03, $01, $02, $03, $01, $02, $03
        .byte $01, $02, $03, $01, $02, $03, $01, $02, $03, $01, $02, $03
        .byte $01, $02, $03, $01, $02, $03, $01, $02, $03, $01, $02, $03

steve_fcol_1
