; Edge validation passed
; Minecraft Steve model with walking animation - generated by gen_steve.py
; 6 boxes, 48 vertices, 72 triangles, 24 animation frames

STEVE_NUM_VERTICES = 48
STEVE_NUM_FACES_0 = 72      ; All faces in single mesh
STEVE_NUM_FACES_1 = 0
STEVE_NUM_FRAMES = 24

steve_vx_0
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_0
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $e2, $e2, $e2, $e2, $88, $88, $88, $88
        .byte $e2, $e2, $e2, $e2, $88, $88, $88, $88
steve_vz_0
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f

steve_vx_1
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_1
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $39, $39, $3f, $3f, $e1, $e1, $e7, $e7
        .byte $3f, $3f, $39, $39, $e7, $e7, $e1, $e1
        .byte $e5, $e5, $df, $df, $8d, $8d, $87, $87
        .byte $df, $df, $e5, $e5, $87, $87, $8d, $8d
steve_vz_1
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $03, $03, $21, $21
        .byte $f1, $f1, $0f, $0f, $df, $df, $fd, $fd
        .byte $f1, $f1, $0f, $0f, $df, $df, $fd, $fd
        .byte $f1, $f1, $0f, $0f, $03, $03, $21, $21

steve_vx_2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_2
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $36, $36, $42, $42, $e3, $e3, $ef, $ef
        .byte $42, $42, $36, $36, $ef, $ef, $e3, $e3
        .byte $e8, $e8, $dc, $dc, $95, $95, $89, $89
        .byte $dc, $dc, $e8, $e8, $89, $89, $95, $95
steve_vz_2
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f2, $f2, $0e, $0e, $15, $15, $30, $30
        .byte $f2, $f2, $0e, $0e, $d0, $d0, $eb, $eb
        .byte $f2, $f2, $0e, $0e, $d0, $d0, $eb, $eb
        .byte $f2, $f2, $0e, $0e, $15, $15, $30, $30

steve_vx_3
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_3
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $34, $34, $44, $44, $e8, $e8, $f7, $f7
        .byte $44, $44, $34, $34, $f7, $f7, $e8, $e8
        .byte $ea, $ea, $da, $da, $9d, $9d, $8e, $8e
        .byte $da, $da, $ea, $ea, $8e, $8e, $9d, $9d
steve_vz_3
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f3, $f3, $0d, $0d, $23, $23, $3c, $3c
        .byte $f3, $f3, $0d, $0d, $c4, $c4, $dd, $dd
        .byte $f3, $f3, $0d, $0d, $c4, $c4, $dd, $dd
        .byte $f3, $f3, $0d, $0d, $23, $23, $3c, $3c

steve_vx_4
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_4
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $33, $33, $45, $45, $ed, $ed, $ff, $ff
        .byte $45, $45, $33, $33, $ff, $ff, $ed, $ed
        .byte $eb, $eb, $d9, $d9, $a5, $a5, $93, $93
        .byte $d9, $d9, $eb, $eb, $93, $93, $a5, $a5
steve_vz_4
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f4, $f4, $0c, $0c, $2d, $2d, $44, $44
        .byte $f4, $f4, $0c, $0c, $bc, $bc, $d3, $d3
        .byte $f4, $f4, $0c, $0c, $bc, $bc, $d3, $d3
        .byte $f4, $f4, $0c, $0c, $2d, $2d, $44, $44

steve_vx_5
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_5
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $32, $32, $46, $46, $f0, $f0, $05, $05
        .byte $46, $46, $32, $32, $05, $05, $f0, $f0
        .byte $ec, $ec, $d8, $d8, $ab, $ab, $96, $96
        .byte $d8, $d8, $ec, $ec, $96, $96, $ab, $ab
steve_vz_5
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f5, $f5, $0b, $0b, $33, $33, $49, $49
        .byte $f5, $f5, $0b, $0b, $b7, $b7, $cd, $cd
        .byte $f5, $f5, $0b, $0b, $b7, $b7, $cd, $cd
        .byte $f5, $f5, $0b, $0b, $33, $33, $49, $49

steve_vx_6
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_6
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $31, $31, $47, $47, $f2, $f2, $07, $07
        .byte $47, $47, $31, $31, $07, $07, $f2, $f2
        .byte $ed, $ed, $d7, $d7, $ad, $ad, $98, $98
        .byte $d7, $d7, $ed, $ed, $98, $98, $ad, $ad
steve_vz_6
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f5, $f5, $0b, $0b, $35, $35, $4a, $4a
        .byte $f5, $f5, $0b, $0b, $b6, $b6, $cb, $cb
        .byte $f5, $f5, $0b, $0b, $b6, $b6, $cb, $cb
        .byte $f5, $f5, $0b, $0b, $35, $35, $4a, $4a

steve_vx_7
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_7
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $32, $32, $46, $46, $f0, $f0, $05, $05
        .byte $46, $46, $32, $32, $05, $05, $f0, $f0
        .byte $ec, $ec, $d8, $d8, $ab, $ab, $96, $96
        .byte $d8, $d8, $ec, $ec, $96, $96, $ab, $ab
steve_vz_7
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f5, $f5, $0b, $0b, $33, $33, $49, $49
        .byte $f5, $f5, $0b, $0b, $b7, $b7, $cd, $cd
        .byte $f5, $f5, $0b, $0b, $b7, $b7, $cd, $cd
        .byte $f5, $f5, $0b, $0b, $33, $33, $49, $49

steve_vx_8
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_8
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $33, $33, $45, $45, $ed, $ed, $ff, $ff
        .byte $45, $45, $33, $33, $ff, $ff, $ed, $ed
        .byte $eb, $eb, $d9, $d9, $a5, $a5, $93, $93
        .byte $d9, $d9, $eb, $eb, $93, $93, $a5, $a5
steve_vz_8
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f4, $f4, $0c, $0c, $2d, $2d, $44, $44
        .byte $f4, $f4, $0c, $0c, $bc, $bc, $d3, $d3
        .byte $f4, $f4, $0c, $0c, $bc, $bc, $d3, $d3
        .byte $f4, $f4, $0c, $0c, $2d, $2d, $44, $44

steve_vx_9
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_9
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $34, $34, $44, $44, $e8, $e8, $f7, $f7
        .byte $44, $44, $34, $34, $f7, $f7, $e8, $e8
        .byte $ea, $ea, $da, $da, $9d, $9d, $8e, $8e
        .byte $da, $da, $ea, $ea, $8e, $8e, $9d, $9d
steve_vz_9
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f3, $f3, $0d, $0d, $23, $23, $3c, $3c
        .byte $f3, $f3, $0d, $0d, $c4, $c4, $dd, $dd
        .byte $f3, $f3, $0d, $0d, $c4, $c4, $dd, $dd
        .byte $f3, $f3, $0d, $0d, $23, $23, $3c, $3c

steve_vx_10
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_10
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $36, $36, $42, $42, $e3, $e3, $ef, $ef
        .byte $42, $42, $36, $36, $ef, $ef, $e3, $e3
        .byte $e8, $e8, $dc, $dc, $95, $95, $89, $89
        .byte $dc, $dc, $e8, $e8, $89, $89, $95, $95
steve_vz_10
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f2, $f2, $0e, $0e, $15, $15, $30, $30
        .byte $f2, $f2, $0e, $0e, $d0, $d0, $eb, $eb
        .byte $f2, $f2, $0e, $0e, $d0, $d0, $eb, $eb
        .byte $f2, $f2, $0e, $0e, $15, $15, $30, $30

steve_vx_11
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_11
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $39, $39, $3f, $3f, $e1, $e1, $e7, $e7
        .byte $3f, $3f, $39, $39, $e7, $e7, $e1, $e1
        .byte $e5, $e5, $df, $df, $8d, $8d, $87, $87
        .byte $df, $df, $e5, $e5, $87, $87, $8d, $8d
steve_vz_11
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $03, $03, $21, $21
        .byte $f1, $f1, $0f, $0f, $df, $df, $fd, $fd
        .byte $f1, $f1, $0f, $0f, $df, $df, $fd, $fd
        .byte $f1, $f1, $0f, $0f, $03, $03, $21, $21

steve_vx_12
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_12
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $e2, $e2, $e2, $e2, $88, $88, $88, $88
        .byte $e2, $e2, $e2, $e2, $88, $88, $88, $88
steve_vz_12
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f

steve_vx_13
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_13
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $3f, $3f, $39, $39, $e7, $e7, $e1, $e1
        .byte $39, $39, $3f, $3f, $e1, $e1, $e7, $e7
        .byte $df, $df, $e5, $e5, $87, $87, $8d, $8d
        .byte $e5, $e5, $df, $df, $8d, $8d, $87, $87
steve_vz_13
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $df, $df, $fd, $fd
        .byte $f1, $f1, $0f, $0f, $03, $03, $21, $21
        .byte $f1, $f1, $0f, $0f, $03, $03, $21, $21
        .byte $f1, $f1, $0f, $0f, $df, $df, $fd, $fd

steve_vx_14
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_14
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $42, $42, $36, $36, $ef, $ef, $e3, $e3
        .byte $36, $36, $42, $42, $e3, $e3, $ef, $ef
        .byte $dc, $dc, $e8, $e8, $89, $89, $95, $95
        .byte $e8, $e8, $dc, $dc, $95, $95, $89, $89
steve_vz_14
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f2, $f2, $0e, $0e, $d0, $d0, $eb, $eb
        .byte $f2, $f2, $0e, $0e, $15, $15, $30, $30
        .byte $f2, $f2, $0e, $0e, $15, $15, $30, $30
        .byte $f2, $f2, $0e, $0e, $d0, $d0, $eb, $eb

steve_vx_15
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_15
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $44, $44, $34, $34, $f7, $f7, $e8, $e8
        .byte $34, $34, $44, $44, $e8, $e8, $f7, $f7
        .byte $da, $da, $ea, $ea, $8e, $8e, $9d, $9d
        .byte $ea, $ea, $da, $da, $9d, $9d, $8e, $8e
steve_vz_15
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f3, $f3, $0d, $0d, $c4, $c4, $dd, $dd
        .byte $f3, $f3, $0d, $0d, $23, $23, $3c, $3c
        .byte $f3, $f3, $0d, $0d, $23, $23, $3c, $3c
        .byte $f3, $f3, $0d, $0d, $c4, $c4, $dd, $dd

steve_vx_16
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_16
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $45, $45, $33, $33, $ff, $ff, $ed, $ed
        .byte $33, $33, $45, $45, $ed, $ed, $ff, $ff
        .byte $d9, $d9, $eb, $eb, $93, $93, $a5, $a5
        .byte $eb, $eb, $d9, $d9, $a5, $a5, $93, $93
steve_vz_16
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f4, $f4, $0c, $0c, $bc, $bc, $d3, $d3
        .byte $f4, $f4, $0c, $0c, $2d, $2d, $44, $44
        .byte $f4, $f4, $0c, $0c, $2d, $2d, $44, $44
        .byte $f4, $f4, $0c, $0c, $bc, $bc, $d3, $d3

steve_vx_17
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_17
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $46, $46, $32, $32, $05, $05, $f0, $f0
        .byte $32, $32, $46, $46, $f0, $f0, $05, $05
        .byte $d8, $d8, $ec, $ec, $96, $96, $ab, $ab
        .byte $ec, $ec, $d8, $d8, $ab, $ab, $96, $96
steve_vz_17
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f5, $f5, $0b, $0b, $b7, $b7, $cd, $cd
        .byte $f5, $f5, $0b, $0b, $33, $33, $49, $49
        .byte $f5, $f5, $0b, $0b, $33, $33, $49, $49
        .byte $f5, $f5, $0b, $0b, $b7, $b7, $cd, $cd

steve_vx_18
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_18
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $47, $47, $31, $31, $07, $07, $f2, $f2
        .byte $31, $31, $47, $47, $f2, $f2, $07, $07
        .byte $d7, $d7, $ed, $ed, $98, $98, $ad, $ad
        .byte $ed, $ed, $d7, $d7, $ad, $ad, $98, $98
steve_vz_18
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f5, $f5, $0b, $0b, $b6, $b6, $cb, $cb
        .byte $f5, $f5, $0b, $0b, $35, $35, $4a, $4a
        .byte $f5, $f5, $0b, $0b, $35, $35, $4a, $4a
        .byte $f5, $f5, $0b, $0b, $b6, $b6, $cb, $cb

steve_vx_19
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_19
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $46, $46, $32, $32, $05, $05, $f0, $f0
        .byte $32, $32, $46, $46, $f0, $f0, $05, $05
        .byte $d8, $d8, $ec, $ec, $96, $96, $ab, $ab
        .byte $ec, $ec, $d8, $d8, $ab, $ab, $96, $96
steve_vz_19
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f5, $f5, $0b, $0b, $b7, $b7, $cd, $cd
        .byte $f5, $f5, $0b, $0b, $33, $33, $49, $49
        .byte $f5, $f5, $0b, $0b, $33, $33, $49, $49
        .byte $f5, $f5, $0b, $0b, $b7, $b7, $cd, $cd

steve_vx_20
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_20
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $45, $45, $33, $33, $ff, $ff, $ed, $ed
        .byte $33, $33, $45, $45, $ed, $ed, $ff, $ff
        .byte $d9, $d9, $eb, $eb, $93, $93, $a5, $a5
        .byte $eb, $eb, $d9, $d9, $a5, $a5, $93, $93
steve_vz_20
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f4, $f4, $0c, $0c, $bc, $bc, $d3, $d3
        .byte $f4, $f4, $0c, $0c, $2d, $2d, $44, $44
        .byte $f4, $f4, $0c, $0c, $2d, $2d, $44, $44
        .byte $f4, $f4, $0c, $0c, $bc, $bc, $d3, $d3

steve_vx_21
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_21
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $44, $44, $34, $34, $f7, $f7, $e8, $e8
        .byte $34, $34, $44, $44, $e8, $e8, $f7, $f7
        .byte $da, $da, $ea, $ea, $8e, $8e, $9d, $9d
        .byte $ea, $ea, $da, $da, $9d, $9d, $8e, $8e
steve_vz_21
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f3, $f3, $0d, $0d, $c4, $c4, $dd, $dd
        .byte $f3, $f3, $0d, $0d, $23, $23, $3c, $3c
        .byte $f3, $f3, $0d, $0d, $23, $23, $3c, $3c
        .byte $f3, $f3, $0d, $0d, $c4, $c4, $dd, $dd

steve_vx_22
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_22
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $42, $42, $36, $36, $ef, $ef, $e3, $e3
        .byte $36, $36, $42, $42, $e3, $e3, $ef, $ef
        .byte $dc, $dc, $e8, $e8, $89, $89, $95, $95
        .byte $e8, $e8, $dc, $dc, $95, $95, $89, $89
steve_vz_22
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f2, $f2, $0e, $0e, $d0, $d0, $eb, $eb
        .byte $f2, $f2, $0e, $0e, $15, $15, $30, $30
        .byte $f2, $f2, $0e, $0e, $15, $15, $30, $30
        .byte $f2, $f2, $0e, $0e, $d0, $d0, $eb, $eb

steve_vx_23
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $e2, $1e, $1e, $e2, $e2, $1e, $1e, $e2
        .byte $1e, $3c, $3c, $1e, $1e, $3c, $3c, $1e
        .byte $c4, $e2, $e2, $c4, $c4, $e2, $e2, $c4
        .byte $00, $1e, $1e, $00, $00, $1e, $1e, $00
        .byte $e2, $00, $00, $e2, $e2, $00, $00, $e2
steve_vy_23
        .byte $78, $78, $78, $78, $3c, $3c, $3c, $3c
        .byte $3c, $3c, $3c, $3c, $e2, $e2, $e2, $e2
        .byte $3f, $3f, $39, $39, $e7, $e7, $e1, $e1
        .byte $39, $39, $3f, $3f, $e1, $e1, $e7, $e7
        .byte $df, $df, $e5, $e5, $87, $87, $8d, $8d
        .byte $e5, $e5, $df, $df, $8d, $8d, $87, $87
steve_vz_23
        .byte $e2, $e2, $1e, $1e, $e2, $e2, $1e, $1e
        .byte $f1, $f1, $0f, $0f, $f1, $f1, $0f, $0f
        .byte $f1, $f1, $0f, $0f, $df, $df, $fd, $fd
        .byte $f1, $f1, $0f, $0f, $03, $03, $21, $21
        .byte $f1, $f1, $0f, $0f, $03, $03, $21, $21
        .byte $f1, $f1, $0f, $0f, $df, $df, $fd, $fd

; Pointer tables for animation frames
steve_vx_lo
        .byte <steve_vx_0
        .byte <steve_vx_1
        .byte <steve_vx_2
        .byte <steve_vx_3
        .byte <steve_vx_4
        .byte <steve_vx_5
        .byte <steve_vx_6
        .byte <steve_vx_7
        .byte <steve_vx_8
        .byte <steve_vx_9
        .byte <steve_vx_10
        .byte <steve_vx_11
        .byte <steve_vx_12
        .byte <steve_vx_13
        .byte <steve_vx_14
        .byte <steve_vx_15
        .byte <steve_vx_16
        .byte <steve_vx_17
        .byte <steve_vx_18
        .byte <steve_vx_19
        .byte <steve_vx_20
        .byte <steve_vx_21
        .byte <steve_vx_22
        .byte <steve_vx_23
steve_vx_hi
        .byte >steve_vx_0
        .byte >steve_vx_1
        .byte >steve_vx_2
        .byte >steve_vx_3
        .byte >steve_vx_4
        .byte >steve_vx_5
        .byte >steve_vx_6
        .byte >steve_vx_7
        .byte >steve_vx_8
        .byte >steve_vx_9
        .byte >steve_vx_10
        .byte >steve_vx_11
        .byte >steve_vx_12
        .byte >steve_vx_13
        .byte >steve_vx_14
        .byte >steve_vx_15
        .byte >steve_vx_16
        .byte >steve_vx_17
        .byte >steve_vx_18
        .byte >steve_vx_19
        .byte >steve_vx_20
        .byte >steve_vx_21
        .byte >steve_vx_22
        .byte >steve_vx_23

steve_vy_lo
        .byte <steve_vy_0
        .byte <steve_vy_1
        .byte <steve_vy_2
        .byte <steve_vy_3
        .byte <steve_vy_4
        .byte <steve_vy_5
        .byte <steve_vy_6
        .byte <steve_vy_7
        .byte <steve_vy_8
        .byte <steve_vy_9
        .byte <steve_vy_10
        .byte <steve_vy_11
        .byte <steve_vy_12
        .byte <steve_vy_13
        .byte <steve_vy_14
        .byte <steve_vy_15
        .byte <steve_vy_16
        .byte <steve_vy_17
        .byte <steve_vy_18
        .byte <steve_vy_19
        .byte <steve_vy_20
        .byte <steve_vy_21
        .byte <steve_vy_22
        .byte <steve_vy_23
steve_vy_hi
        .byte >steve_vy_0
        .byte >steve_vy_1
        .byte >steve_vy_2
        .byte >steve_vy_3
        .byte >steve_vy_4
        .byte >steve_vy_5
        .byte >steve_vy_6
        .byte >steve_vy_7
        .byte >steve_vy_8
        .byte >steve_vy_9
        .byte >steve_vy_10
        .byte >steve_vy_11
        .byte >steve_vy_12
        .byte >steve_vy_13
        .byte >steve_vy_14
        .byte >steve_vy_15
        .byte >steve_vy_16
        .byte >steve_vy_17
        .byte >steve_vy_18
        .byte >steve_vy_19
        .byte >steve_vy_20
        .byte >steve_vy_21
        .byte >steve_vy_22
        .byte >steve_vy_23

steve_vz_lo
        .byte <steve_vz_0
        .byte <steve_vz_1
        .byte <steve_vz_2
        .byte <steve_vz_3
        .byte <steve_vz_4
        .byte <steve_vz_5
        .byte <steve_vz_6
        .byte <steve_vz_7
        .byte <steve_vz_8
        .byte <steve_vz_9
        .byte <steve_vz_10
        .byte <steve_vz_11
        .byte <steve_vz_12
        .byte <steve_vz_13
        .byte <steve_vz_14
        .byte <steve_vz_15
        .byte <steve_vz_16
        .byte <steve_vz_17
        .byte <steve_vz_18
        .byte <steve_vz_19
        .byte <steve_vz_20
        .byte <steve_vz_21
        .byte <steve_vz_22
        .byte <steve_vz_23
steve_vz_hi
        .byte >steve_vz_0
        .byte >steve_vz_1
        .byte >steve_vz_2
        .byte >steve_vz_3
        .byte >steve_vz_4
        .byte >steve_vz_5
        .byte >steve_vz_6
        .byte >steve_vz_7
        .byte >steve_vz_8
        .byte >steve_vz_9
        .byte >steve_vz_10
        .byte >steve_vz_11
        .byte >steve_vz_12
        .byte >steve_vz_13
        .byte >steve_vz_14
        .byte >steve_vz_15
        .byte >steve_vz_16
        .byte >steve_vz_17
        .byte >steve_vz_18
        .byte >steve_vz_19
        .byte >steve_vz_20
        .byte >steve_vz_21
        .byte >steve_vz_22
        .byte >steve_vz_23

; Face indices (constant across all frames)
steve_fi_0
        .byte $00, $00, $02, $02, $00, $00, $04, $04, $01, $01, $00, $00
        .byte $08, $08, $0a, $0a, $08, $08, $0c, $0c, $09, $09, $08, $08
        .byte $10, $10, $12, $12, $10, $10, $14, $14, $11, $11, $10, $10
        .byte $18, $18, $1a, $1a, $18, $18, $1c, $1c, $19, $19, $18, $18
        .byte $20, $20, $22, $22, $20, $20, $24, $24, $21, $21, $20, $20
        .byte $28, $28, $2a, $2a, $28, $28, $2c, $2c, $29, $29, $28, $28

steve_fj_0
        .byte $01, $05, $03, $07, $03, $02, $05, $06, $02, $06, $04, $07
        .byte $09, $0d, $0b, $0f, $0b, $0a, $0d, $0e, $0a, $0e, $0c, $0f
        .byte $11, $15, $13, $17, $13, $12, $15, $16, $12, $16, $14, $17
        .byte $19, $1d, $1b, $1f, $1b, $1a, $1d, $1e, $1a, $1e, $1c, $1f
        .byte $21, $25, $23, $27, $23, $22, $25, $26, $22, $26, $24, $27
        .byte $29, $2d, $2b, $2f, $2b, $2a, $2d, $2e, $2a, $2e, $2c, $2f

steve_fk_0
        .byte $05, $04, $07, $06, $02, $01, $06, $07, $06, $05, $07, $03
        .byte $0d, $0c, $0f, $0e, $0a, $09, $0e, $0f, $0e, $0d, $0f, $0b
        .byte $15, $14, $17, $16, $12, $11, $16, $17, $16, $15, $17, $13
        .byte $1d, $1c, $1f, $1e, $1a, $19, $1e, $1f, $1e, $1d, $1f, $1b
        .byte $25, $24, $27, $26, $22, $21, $26, $27, $26, $25, $27, $23
        .byte $2d, $2c, $2f, $2e, $2a, $29, $2e, $2f, $2e, $2d, $2f, $2b

; Empty second mesh
steve_fi_1
steve_fj_1
steve_fk_1

; Face colors
steve_fcol_0
        .byte $01, $01, $01, $01, $01, $01, $01, $01, $02, $02, $02, $02
        .byte $03, $03, $03, $03, $03, $03, $03, $03, $02, $02, $02, $02
        .byte $01, $01, $01, $01, $01, $01, $01, $01, $02, $02, $02, $02
        .byte $01, $01, $01, $01, $01, $01, $01, $01, $02, $02, $02, $02
        .byte $01, $01, $01, $01, $01, $01, $01, $01, $02, $02, $02, $02
        .byte $01, $01, $01, $01, $01, $01, $01, $01, $02, $02, $02, $02

steve_fcol_1
